# Generated by Django 2.0.5 on 2018-05-16 12:57

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Emission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('priority', models.PositiveIntegerField(default=0, verbose_name='Priority')),
                ('is_repeat', models.BooleanField(default=False, verbose_name='Is Repeat')),
                ('is_live', models.BooleanField(default=True, verbose_name='Is Live')),
                ('start', models.DateField(verbose_name='Start')),
                ('end', models.DateField(blank=True, verbose_name='End')),
                ('start_time', models.DateTimeField(verbose_name='Start Time')),
                ('end_time', models.DateTimeField(blank=True, verbose_name='End Time')),
            ],
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('target', models.URLField(verbose_name='Target')),
                ('icon', models.CharField(blank=True, max_length=100, verbose_name='Icon')),
            ],
            options={
                'verbose_name': 'Link',
                'verbose_name_plural': 'Links',
            },
        ),
        migrations.CreateModel(
            name='LinkTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('target_template', models.CharField(max_length=255, verbose_name='Target template')),
                ('icon', models.CharField(blank=True, max_length=100, verbose_name='Icon')),
                ('help_text', models.TextField(verbose_name='Help Text')),
            ],
            options={
                'verbose_name': 'Link Template',
                'verbose_name_plural': 'Link Templates',
            },
        ),
        migrations.CreateModel(
            name='Show',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('website', models.URLField(blank=True, verbose_name='Website')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
                ('start', models.DateField(verbose_name='Start')),
                ('end', models.DateField(blank=True, verbose_name='End')),
                ('links', models.ManyToManyField(to='badia.Link', verbose_name='Links')),
            ],
            options={
                'ordering': ['-active', 'name'],
                'verbose_name': 'Show',
                'verbose_name_plural': 'Shows',
            },
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('website', models.URLField(blank=True, verbose_name='Website')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
            ],
            options={
                'ordering': ['-active', 'name'],
                'verbose_name': 'Station',
                'verbose_name_plural': 'Stations',
            },
        ),
        migrations.AddField(
            model_name='show',
            name='station',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shows', to='badia.Station', verbose_name='Station'),
        ),
        migrations.AddField(
            model_name='emission',
            name='show',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='emissions', to='badia.Show', verbose_name='Emissions'),
        ),
    ]
